// global variables start
const $onClickRoll5 = $('.onClickRoll5');  
const $onClickRoll4 = $('.onClickRoll4');
const $onClickRoll3 = $('.onClickRoll3');  
const $onClickRoll2 = $('.onClickRoll2');
const $onClickRoll1 = $('.onClickRoll1');
// global variables end

//create a random number each time function is called.
function grabRandomNum() {
  let randomNum = Math.floor(Math.random() * 6) + 1; //number from 1-6
  return randomNum;
}
//DOM click event listeners that will generate the right number of 1-6 numbers according to the button clicked. 

//generates 5 random numbers from 1-6 and pastes them into the DOM. 
$onClickRoll5.click(function(){//creates the click function.
    //selects the element with the correct ID and pastes in new DOM elements including the random number generated by the RandomNum() function. 
    $('.dice-button').html('<h4 class="rolled-title">You rolled:</h4><button class="btn_1">' + grabRandomNum() + '</button><button class="btn_2">' + grabRandomNum() + '</button><button class="btn_3">' + grabRandomNum() + '</button><button class="btn_4">' + grabRandomNum() + '</button><button class="btn_5">' + grabRandomNum() + '</button>');
});


$onClickRoll4.click(function(){
    $('.dice-button').html('<h4 class="rolled-title">You rolled:</h4><button class="btn_1">' + grabRandomNum() + '</button><button class="btn_2">' + grabRandomNum() + '</button><button class="btn_3">' + grabRandomNum() + '</button><button class="btn_4">' + grabRandomNum() + '</button>');
  });

$onClickRoll3.click(function(){
    $('.dice-button').html('<h4 class="rolled-title">You rolled:</h4><button class="btn_1">' + grabRandomNum() + '</button><button class="btn_2">' + grabRandomNum() + '</button><button class="btn_3">' + grabRandomNum() + '</button>');
});

$onClickRoll2.click(function(){
    $('.dice-button').html('<h4 class="rolled-title">You rolled:</h4><button class="btn_1">' + grabRandomNum() + '</button><button class="btn_2">' + grabRandomNum() + '</button>');
  });
 
$onClickRoll1.click(function(){
    $('.dice-button').html('<h4 class="rolled-title">You rolled:</h4><button class="btn_1">' + grabRandomNum() + '</button>');
});


//grabs the value of the randomly generated number after it's been rolled.
$(".dice-button").on("click", ".btn_1", function() { 
    //pastes the number value clicked on into the input field
    $(".myInput").val($(".myInput").val() + this.textContent + ", ");
});

$(".dice-button").on("click", ".btn_2", function() {
    $(".myInput").val($(".myInput").val() + this.textContent + ", ");
});

$(".dice-button").on("click", ".btn_3", function() {
    $(".myInput").val($(".myInput").val() + this.textContent + ", ");
});

$(".dice-button").on("click", ".btn_4", function() {
    $(".myInput").val($(".myInput").val() + this.textContent + ", ");
});

$(".dice-button").on("click", ".btn_5", function() {
    $(".myInput").val($(".myInput").val() + this.textContent + ", "); 
});


//clears the input field when clear button is clicked
$(".clearInput").click(function(){
    $(".myInput").val("");
})



//Note that button elements have an attribute you can set called “disabled” that when set to true will not respond to user clicks. See the MDN documentation for more details.